name: chargepassv4
description: A Flutter-based password management app with Firebase integration, encryption, and UI customization.

version: 1.0.9+1

environment:
  sdk: ">=3.4.0 <4.0.0"

homepage: https://github.com/UPT-FAING-EPIS/chargepassv4
repository: https://github.com/UPT-FAING-EPIS/chargepassv4
issue_tracker: https://github.com/UPT-FAING-EPIS/chargepassv4/issues
documentation: https://github.com/UPT-FAING-EPIS/chargepassv4#readme

maintainer: Edgard Reynaldo <ec2019064917@virtual.upt.pe>

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.6
  firebase_storage: ^12.4.5
  firebase_auth: ^5.5.2
  uuid: ^4.5.1
  flutter_signin_button: ^2.0.0
  flutter_iconly: ^1.0.2
  firebase_app_check: ^0.3.2+5
  intl: ^0.20.2
  firebase_messaging: ^15.2.5
  http: ^1.3.0
  iconly: ^1.0.1
  package_info_plus: ^8.3.0
  url_launcher: ^6.3.1
  encrypt: ^5.0.3
  provider: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logcharge.png
    - assets/logchar.png

false_secrets:
  - /lib/firebase_options.dart
  - /lib/config/firebase_options.dart
  - /android/app/google-services.json
