name: Publish Flutter Package to pub.dev

on:
  push:
    paths:
      - 'chargepassv4/pubspec.yaml'  # Ajusta si el path es diferente
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: chargepassv4  # Ajusta si es necesario

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'

      - name: Set pub.dev credentials
        run: |
          mkdir -p ~/.pub-cache
          echo '${{ secrets.PUB_CREDENTIALS }}' > ~/.pub-cache/credentials.json

      - name: Install dependencies
        run: flutter pub get

      - name: Extract version from pubspec.yaml
        id: version
        run: |
          VERSION=$(grep '^version:' pubspec.yaml | awk '{print $2}' | cut -d '+' -f1)
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Create tag from pubspec.yaml version (if not exists)
        run: |
          TAG="v${{ steps.version.outputs.VERSION }}"
          if git rev-parse "$TAG" >/dev/null 2>&1; then
            echo "Tag $TAG already exists. Skipping tag creation."
          else
            git config --global user.name "github-actions"
            git config --global user.email "github-actions@github.com"
            git tag $TAG
            git push origin $TAG
          fi

      - name: Publish package to pub.dev
        run: flutter pub publish -f
