name: Auto Release Flutter App from pubspec.yaml

on:
  push:
    paths:
      - 'chargepassv4/pubspec.yaml'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Extract version from pubspec.yaml
        id: version
        run: |
          VERSION=$(grep '^version:' chargepassv4/pubspec.yaml | awk '{print $2}' | cut -d '+' -f1)
          echo "Version encontrada: $VERSION"
          echo "version=v$VERSION" >> $GITHUB_OUTPUT

      - name: Create tag
        run: |
          git tag ${{ steps.version.outputs.version }}
          git push origin ${{ steps.version.outputs.version }}

      - name: Compress Flutter project
        run: |
          cd chargepassv4
          zip -r ../chargepassv4-${{ steps.version.outputs.version }}.zip .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.version }}
          name: Release ${{ steps.version.outputs.version }}
          files: chargepassv4-${{ steps.version.outputs.version }}.zip
          make_latest: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
